name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13"]
        prerelease: [false]
        include:
          - python-version: "3.13"
            prerelease: true

    name: Python ${{ matrix.python-version }}${{ matrix.prerelease && ' (pre-release)' || '' }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock
      - name: Install dependencies
        run: uv sync --group test
        env:
          UV_PRERELEASE: ${{ matrix.prerelease && 'allow' || '' }}
      - name: Run tests
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
        run: uv run pytest --cov --cov-report=xml -v
      - name: Upload coverage
        uses: codecov/codecov-action@v5

  check:
    name: Tests pass
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
